"""Fetch the frozen SOURCE CLIPS for the video_edit scenarios from Pexels Video
(the sheet's licence-clean route: "Free to use", commercial OK, no attribution).

Why Pexels and not the sheet's other options: LOVEU-TGVE-2023 ships 480x480
frame folders in a Google Drive zip (no MP4s; TGVE+ metadata is CC-BY-NC),
and DAVIS is research-licensed. And per the study lead: source clips are
never generated by one of the models under test — real footage only, so no
arm edits its own output.

How: Pexels' sized download endpoint, /download/video/<id>/?h=720&w=1280,
returns the landscape 1280x720 MP4 directly (and 404s for portrait clips,
which is exactly the orientation filter the scenario gates need). No page
scraping — the HTML pages rate-limit to 403 after a few dozen hits.

Per scenario a short candidate list, chosen by title from Pexels search on
2026-09-03 — content is NOT machine-verified; eyeball before a paid run.
  * the first candidate that serves a 1280x720 file under 40 MB wins
  * VID-EDIT-06 needs a ~5 s clip: candidates are downloaded and measured
    with the project's own MP4 parser; the first with 4-6 s wins, others are
    deleted (the shortest is kept, flagged, if none fits)
  * VID-EDIT-10 edits "the previously edited clip" — derived from the
    VID-EDIT-08 output at run time; nothing to fetch

Idempotent: existing files are never re-downloaded. Sidecar per clip: pexels
id, page + file URL, licence, parsed duration/dims, size, sha256.

    python assets/fetch_edit_clips.py            # fetch what's missing
    python assets/fetch_edit_clips.py --dry-run  # resolve only (HEAD-style), no files kept
"""
from __future__ import annotations

import hashlib
import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import httpx

VIDEO = Path(__file__).resolve().parent.parent
OUT = VIDEO / "assets" / "bank"
sys.path.insert(0, str(VIDEO))
from runner.video.checks import parse_mp4  # noqa: E402

UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/128.0 Safari/537.36")
LICENCE = ("Pexels License — free to use, commercial use permitted, no attribution "
           "required (https://www.pexels.com/license/)")
MAX_BYTES = 40 * 1024 * 1024
PAUSE_S = 1.5

# scenario -> (what the brief needs, [candidate pexels ids in preference order])
PLAN = {
    "VID-EDIT-01": ("clip with a red umbrella",
                    [4631118, 4631120, 19277501, 39273129, 36147943, 854367]),
    "VID-EDIT-02": ("parked bicycle in the background behind a subject",
                    [25751902, 5293765, 4649966, 5792243, 6374783]),
    "VID-EDIT-03": ("a person (background will be replaced)",
                    [7086113, 5665059, 8085542, 4347098, 5240128]),
    "VID-EDIT-04": ("daytime clip (to be re-lit as dusk)",
                    [33632016, 854367, 5240128, 4347098, 14395658]),
    "VID-EDIT-05": ("table with an empty end",
                    [6612210, 6633339, 7555156, 5921201]),
    "VID-EDIT-07": ("static-camera clip",
                    [7677715, 5644247, 6612210, 6800490]),
    "VID-EDIT-08": ("person in a jacket, a sign behind, sky visible",
                    [25747098, 6324858, 14395658, 33632016, 8084886]),
    "VID-EDIT-09": ("on-screen text reading SALE",
                    [5836560, 5889067, 6114425, 5644247]),
}
# EDIT-06: any landscape clip whose measured duration is 4-6 s
SHORT_POOL = [4615494, 6800490, 7677715, 5644247, 6612210, 5240128, 5665059,
              4347098, 7086113, 6324858, 5836560, 5889067]


def sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def utcnow() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


class Pexels:
    def __init__(self):
        self.http = httpx.Client(follow_redirects=True, timeout=180,
                                 headers={"User-Agent": UA, "Accept": "*/*"})

    def url(self, vid: int) -> str:
        return f"https://www.pexels.com/download/video/{vid}/?h=720&w=1280"

    def probe(self, vid: int) -> dict | None:
        """200 + video/mp4 + a sane size => a landscape 720p file exists."""
        with self.http.stream("GET", self.url(vid)) as r:
            ok = (r.status_code == 200
                  and r.headers.get("content-type", "").startswith("video/"))
            size = int(r.headers.get("content-length") or 0)
            final = str(r.url)
        time.sleep(PAUSE_S)
        if not ok:
            return None
        if size and size > MAX_BYTES:
            print(f"      {vid}: {size / 1e6:.0f} MB > cap — skipped")
            return None
        return {"id": vid, "file_url": final, "bytes_hdr": size,
                "page_url": f"https://www.pexels.com/video/{vid}/"}

    def download(self, vid: int, out: Path) -> None:
        with self.http.stream("GET", self.url(vid)) as r:
            r.raise_for_status()
            with open(out, "wb") as fh:
                for chunk in r.iter_bytes():
                    fh.write(chunk)
        time.sleep(PAUSE_S)


def write_sidecar(out: Path, info: dict, sid: str, need: str, parsed: dict, note: str) -> None:
    meta = {"source": "Pexels Video", "pexels_id": info["id"], "page_url": info["page_url"],
            "file_url": info["file_url"], "licence": LICENCE, "scenario": sid,
            "brief_need": need, "parsed": parsed, "bytes": out.stat().st_size,
            "sha256": sha256(out), "ts": utcnow(),
            "match_note": "chosen by title from Pexels search; content not "
                          "machine-verified — eyeball before a paid run" + note}
    out.with_suffix(".json").write_text(json.dumps(meta, indent=1) + "\n")


def fetch_first(px: Pexels, sid: str, need: str, cands: list[int], dry: bool) -> bool:
    out = OUT / f"{sid}-source.mp4"
    for vid in cands:
        info = px.probe(vid)
        if info is None:
            print(f"      {vid}: no landscape 720p file (portrait/unavailable) — skipped")
            continue
        print(f"  {sid}: pexels {vid} ({info['bytes_hdr'] / 1e6:.1f} MB)  <- {need}")
        if dry:
            return True
        px.download(vid, out)
        parsed = parse_mp4(out)
        write_sidecar(out, info, sid, need, parsed, "")
        print(f"      ok {out.name}: {parsed['width']}x{parsed['height']} "
              f"{parsed['duration_s']:.1f}s {out.stat().st_size / 1e6:.1f} MB")
        return True
    print(f"  {sid}: NO usable candidate — needs a manual pick")
    return False


def fetch_short(px: Pexels, dry: bool) -> None:
    sid, need = "VID-EDIT-06", "five-second clip (to be extended to eight)"
    out = OUT / f"{sid}-source.mp4"
    tmp = OUT / f"{sid}-candidate.tmp.mp4"
    best: tuple[float, int, dict] | None = None
    for vid in SHORT_POOL:
        info = px.probe(vid)
        if info is None:
            continue
        if dry:
            print(f"  {sid}: candidate pexels {vid} ({info['bytes_hdr'] / 1e6:.1f} MB)")
            continue
        px.download(vid, tmp)
        d = parse_mp4(tmp)["duration_s"]
        print(f"      {vid}: {d:.1f}s")
        if 4.0 <= d <= 6.0:
            tmp.rename(out)
            if best is not None:                 # a shorter-but-wrong runner-up was kept
                best[2]["path"].unlink(missing_ok=True)
            write_sidecar(out, info, sid, need, parse_mp4(out), "")
            print(f"  {sid}: pexels {vid} ({d:.1f}s)  <- {need}")
            return
        if best is None or d < best[0]:
            if best is not None:
                best[2]["path"].unlink(missing_ok=True)
            keep = OUT / f"{sid}-shortest.tmp.mp4"
            tmp.rename(keep)
            best = (d, vid, {**info, "path": keep})
        else:
            tmp.unlink(missing_ok=True)
    if dry:
        return
    if best is None:
        print(f"  {sid}: NO usable candidate")
        return
    d, vid, info = best
    info["path"].rename(out)
    write_sidecar(out, info, sid, need, parse_mp4(out),
                  f"; WARNING no 4-6 s candidate found, shortest available ({d:.1f}s) used")
    print(f"  {sid}: pexels {vid} ({d:.1f}s, WARNING: not 4-6 s)  <- {need}")


def main(argv: list[str]) -> int:
    dry = "--dry-run" in argv
    OUT.mkdir(parents=True, exist_ok=True)
    px = Pexels()
    print(f"[clips] output: {OUT}  {'(DRY RUN)' if dry else ''}")
    for sid, (need, cands) in PLAN.items():
        if (OUT / f"{sid}-source.mp4").exists():
            print(f"  {sid}: exists, skipped")
            continue
        fetch_first(px, sid, need, cands, dry)
    if not (OUT / "VID-EDIT-06-source.mp4").exists():
        fetch_short(px, dry)
    print("  VID-EDIT-10: derived from the VID-EDIT-08 output at run time — nothing to fetch")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
