// generated by build.py -- do not edit
window.PANEL = {
  "builtAt": "2026-09-10T09:51:49+00:00",
  "manifestHash": "f0d28bf5804b023c",
  "sourceRun": "2026-09-09_041808_voice-p1",
  "take": "p1",
  "arms": 2,
  "note": "model identities are in reveal.json, which is not shipped",
  "cards": [
    {
      "id": "voi-ret-01",
      "attn": false,
      "task": "text_to_speech",
      "lang": "en-IN",
      "style": null,
      "title": "Conversational product recommendation - E-commerce / Retail",
      "script": "I found two options that match your requirements for a lightweight laptop under seventy-five thousand rupees. The ASUS Vivobook S 14 has sixteen gigabytes of RAM, a five-hundred-and-twelve-gigabyte SSD, and a fourteen-inch OLED display. It is currently priced at sixty-nine thousand nine hundred and ninety-nine rupees. If you prefer a larger screen, the Lenovo IdeaPad Slim 5 has sixteen gigabytes of RAM, a one-terabyte SSD, and a sixteen-inch display for seventy-two thousand four hundred and ninety rupees. Both models are available for delivery by Friday, and the Lenovo includes a three-year extended warranty. Based on your preference for battery life and a larger display, I would recommend the Lenovo.",
      "target_rms_dbfs": -18.86,
      "pair": [
        {
          "clip": "c_14558db34eee",
          "gain": 0.975
        },
        {
          "clip": "c_d21b4465c17f",
          "gain": 1.0
        }
      ]
    },
    {
      "id": "voi-tel-01",
      "attn": false,
      "task": "text_to_speech",
      "lang": "en-IN",
      "style": null,
      "title": "Order number readback - Transactional / telephony",
      "script": "Your order number is 4471 8802 3915.",
      "target_rms_dbfs": -20.15,
      "pair": [
        {
          "clip": "c_030b7c328bc7",
          "gain": 0.7665
        },
        {
          "clip": "c_4e09c32e84bb",
          "gain": 1.0
        }
      ]
    },
    {
      "id": "voi-tel-02",
      "attn": false,
      "task": "text_to_speech",
      "lang": "en-IN",
      "style": null,
      "title": "Currency confirmation - Transactional / telephony",
      "script": "The amount is four thousand two hundred and fifty rupees and seventy-five paise.",
      "target_rms_dbfs": -18.5,
      "pair": [
        {
          "clip": "c_a07fa28f79b9",
          "gain": 1.0
        },
        {
          "clip": "c_ef1d1edf6797",
          "gain": 0.9886
        }
      ]
    },
    {
      "id": "voi-tel-06",
      "attn": false,
      "task": "text_to_speech",
      "lang": "en-IN",
      "style": null,
      "title": "Phone number readback - Transactional / telephony",
      "script": "Your number is 98450 12345.",
      "target_rms_dbfs": -18.62,
      "pair": [
        {
          "clip": "c_958d8857839d",
          "gain": 1.0
        },
        {
          "clip": "c_ba9169002fd7",
          "gain": 0.9943
        }
      ]
    },
    {
      "id": "voi-tel-08",
      "attn": false,
      "task": "text_to_speech",
      "lang": "en-IN",
      "style": null,
      "title": "OTP digit sequence - Transactional / telephony",
      "script": "Your one-time code is 7 3 9 1 5 2.",
      "target_rms_dbfs": -21.25,
      "pair": [
        {
          "clip": "c_5e41e972ab57",
          "gain": 0.7405
        },
        {
          "clip": "c_e41fb64b1ee9",
          "gain": 1.0
        }
      ]
    },
    {
      "id": "voi-tel-09",
      "attn": false,
      "task": "text_to_speech",
      "lang": "en-IN",
      "style": null,
      "title": "Card last-four confirmation - Transactional / telephony",
      "script": "Your card ending in 4419 has been confirmed.",
      "target_rms_dbfs": -21.42,
      "pair": [
        {
          "clip": "c_9e3751e0ef2e",
          "gain": 0.6653
        },
        {
          "clip": "c_cb5493e2a2cf",
          "gain": 1.0
        }
      ]
    },
    {
      "id": "vr-ads-02",
      "attn": false,
      "task": "styled_tts",
      "lang": "en-IN",
      "style": "upbeat retail radio read, warm but brisk",
      "title": "Fifteen-second broadcast spot, exact duration - Ads",
      "script": "Monsoon's here. So is the Kalyani Motors service camp. Free twenty-one point inspection, wiper and brake-pad check, up to thirty percent off parts. Three days only, at all fourteen Bengaluru branches. Kalyani Motors. Drive the monsoon, don't dread it.",
      "target_rms_dbfs": -17.79,
      "pair": [
        {
          "clip": "c_54f2013066ba",
          "gain": 0.9365
        },
        {
          "clip": "c_ff75ec1ba0b4",
          "gain": 1.0
        }
      ]
    },
    {
      "id": "vr-ads-05",
      "attn": false,
      "task": "styled_tts",
      "lang": "en-IN",
      "style": "bright retail beauty read, warm and quick",
      "title": "Brand name pronunciation, no markup permitted - Ads",
      "script": "This season, Nykaa brings you three days of beauty. Save up to forty percent at Nykaa, plus an extra ten percent with Jio Pay. Discover Kaya Clinic favourites, Cetaphil essentials, and the full Nykaa Naturals range. Nykaa. Three days only. Kaya, Cetaphil and Jio Pay offers apply while stocks last.",
      "target_rms_dbfs": -20.16,
      "pair": [
        {
          "clip": "c_a74af623d384",
          "gain": 1.0
        },
        {
          "clip": "c_f8281ddf4a62",
          "gain": 0.8156
        }
      ]
    },
    {
      "id": "vr-ads-06",
      "attn": false,
      "task": "styled_tts",
      "lang": "en-IN",
      "style": "fast statutory disclaimer read, flat and even, fully articulated",
      "title": "Compliance disclaimer at broadcast pace - Ads",
      "script": "Credit is subject to status and affordability checks. Representative APR twenty-four point nine percent variable. Minimum repayment two thousand five hundred rupees per month over thirty-six months. Missing payments may affect your credit rating. Terms, conditions and eligibility criteria apply. Kalyani Finance is a registered non-banking financial company.",
      "target_rms_dbfs": -20.14,
      "pair": [
        {
          "clip": "c_0df7fe6b223d",
          "gain": 1.0
        },
        {
          "clip": "c_62e28007ac2d",
          "gain": 0.8346
        }
      ]
    },
    {
      "id": "vr-drama-01",
      "attn": false,
      "task": "styled_tts",
      "lang": "en-GB",
      "style": "warm serialised storytelling, one consistent narrator",
      "title": "Episodic narration, voice held across sessions - Micro-drama",
      "script": "The lamps along the causeway came on one at a time, the way they always did, and Sarala counted them without meaning to. Eleven, twelve, thirteen. By the fourteenth she had reached the turning, and by the fifteenth she had decided. She would not go back to the house tonight. She would walk until the road ran out, and then she would see what the sea had to say about it.",
      "target_rms_dbfs": -24.76,
      "pair": [
        {
          "clip": "c_05eafabcdf8d",
          "gain": 1.0
        },
        {
          "clip": "c_f41ac7ad7dca",
          "gain": 0.5352
        }
      ]
    },
    {
      "id": "vr-drama-02",
      "attn": false,
      "task": "text_to_speech",
      "lang": "en-GB",
      "style": "measured literary narration, third person, unhurried",
      "title": "Narration to ACX submission spec - Micro-drama & entertainment",
      "script": "The harbour at Vathy had been awake for an hour before Ilse reached it. She came down the cut between the chandlery and the ice house with her collar turned up, counting the boats as she always did, and found the Kerensa gone from her mooring. Nobody had thought to telephone. The berth held nothing but a coil of blue rope and the flat grey water closing over where the hull had been. Ilse stood there long enough for the light to change. Then she walked back up the cut, past the chandlery, past the ice house, and knocked on a door she had promised herself she would never knock on again.",
      "target_rms_dbfs": -24.45,
      "pair": [
        {
          "clip": "c_2315414b9812",
          "gain": 0.5735
        },
        {
          "clip": "c_6381ca0a8865",
          "gain": 1.0
        }
      ]
    },
    {
      "id": "vr-drama-04",
      "attn": false,
      "task": "styled_tts",
      "lang": "en-IN",
      "style": "controlled anger held just under the surface, not shouted",
      "title": "Dubbed line fitted to an 11.0s shot - Micro-drama & entertainment",
      "script": "You said you would come back before the monsoon. I waited. The house is still standing, and so am I. But do not mistake that for forgiveness.",
      "target_rms_dbfs": -25.89,
      "pair": [
        {
          "clip": "c_ae49ed17f975",
          "gain": 0.4266
        },
        {
          "clip": "c_dcc5c9a6ffb6",
          "gain": 1.0
        }
      ]
    },
    {
      "id": "vr-ecom-01",
      "attn": false,
      "task": "text_to_speech",
      "lang": "en-IN",
      "style": null,
      "title": "WISMO order status readback - Ecommerce & Retail",
      "script": "Thank you for holding. I have found your order. The reference is 4 8 1 9 0 2 7 7 3 1 5 4. Your parcel left our Bhiwandi facility this morning and is with Blue Dart. Delivery is scheduled for Thursday the fourteenth, between two and four in the afternoon. Shall I send the confirmation to your registered mobile ending 6 3 0 2?",
      "target_rms_dbfs": -18.55,
      "pair": [
        {
          "clip": "c_3360dfa00fe8",
          "gain": 1.0
        },
        {
          "clip": "c_7c458102fe35",
          "gain": 0.9806
        }
      ]
    },
    {
      "id": "vr-ecom-02",
      "attn": false,
      "task": "styled_tts",
      "lang": "en-IN",
      "style": "warm outbound service call, helpful and unhurried, never pushy",
      "title": "Cart-recovery call, agent turn only - Ecommerce & Retail",
      "script": "Hi, this is Meera calling from Urban Ladder. I noticed you were looking at the Fenton three-seater sofa but did not complete your order, and I wanted to check whether something got in the way. If it was the delivery timeline, we can get it to you in nine days rather than the fourteen shown at checkout. And your cart is still saved. Would it help if I sent the checkout link to your registered number?",
      "target_rms_dbfs": -21.31,
      "pair": [
        {
          "clip": "c_8032c694afac",
          "gain": 1.0
        },
        {
          "clip": "c_cbd71a268ffa",
          "gain": 0.7071
        }
      ]
    },
    {
      "id": "vr-ecom-03",
      "attn": false,
      "task": "text_to_speech",
      "lang": "en-IN",
      "style": null,
      "title": "Refund confirmation in Indian numbering - Ecommerce & Retail",
      "script": "Your refund has been approved. The full amount of Rs 2,50,000 will be credited to the UPI account ending 4 4 1 9 within seven working days. Your reference number for this refund is 9 0 3 7 6 2. If the amount has not appeared after seven working days, please call us back and quote that reference.",
      "target_rms_dbfs": -20.41,
      "pair": [
        {
          "clip": "c_cb863c5253d3",
          "gain": 0.867
        },
        {
          "clip": "c_f12baa2e1a95",
          "gain": 1.0
        }
      ]
    },
    {
      "id": "vr-ecom-04",
      "attn": false,
      "task": "text_to_speech",
      "lang": "en-IN",
      "style": null,
      "title": "After-hours booking readback - Ecommerce & Retail",
      "script": "Lovely, that is all confirmed. Let me read it back to you. A table for seven, on Saturday the twenty-second of November, at eight in the evening, under the name Raghavan. We will hold the table for fifteen minutes past the booking time. If anything changes, call us on 9 8 4 5 0 2 7 7 1 6. We look forward to seeing you.",
      "target_rms_dbfs": -19.54,
      "pair": [
        {
          "clip": "c_0d9da1ceca4d",
          "gain": 0.8404
        },
        {
          "clip": "c_e9e97b760b54",
          "gain": 1.0
        }
      ]
    },
    {
      "id": "vr-ecom-06#bare",
      "attn": false,
      "task": "text_to_speech",
      "lang": null,
      "style": null,
      "title": "KYC readback, confusable characters - Ecommerce & Retail",
      "script": "Your verification reference is B 8 Q O Z 2 G 6. Please also confirm the card ending 4 4 1 9.",
      "target_rms_dbfs": -21.1,
      "pair": [
        {
          "clip": "c_7b6c0540da3f",
          "gain": 1.0
        },
        {
          "clip": "c_b02afc2ca5d1",
          "gain": 0.6808
        }
      ]
    },
    {
      "id": "vr-ecom-06#nato",
      "attn": false,
      "task": "text_to_speech",
      "lang": null,
      "style": null,
      "title": "KYC readback, confusable characters - Ecommerce & Retail",
      "script": "Your verification reference is Bravo, eight, Quebec, Oscar, Zulu, two, Golf, six. Please also confirm the card ending 4 4 1 9.",
      "target_rms_dbfs": -20.61,
      "pair": [
        {
          "clip": "c_5e8bfdf36419",
          "gain": 0.695
        },
        {
          "clip": "c_e0dc873ddbc8",
          "gain": 1.0
        }
      ]
    },
    {
      "id": "vr-ecom-07",
      "attn": false,
      "task": "text_to_speech",
      "lang": "en-IN",
      "style": null,
      "title": "Cost per finished minute at volume - Ecommerce & Retail",
      "script": "Thank you for calling. Your order is confirmed and will arrive on Thursday. Is there anything else I can help you with today?",
      "target_rms_dbfs": -18.66,
      "pair": [
        {
          "clip": "c_4b99ebd0393d",
          "gain": 1.0
        },
        {
          "clip": "c_e9e579b94010",
          "gain": 0.9215
        }
      ]
    },
    {
      "id": "vr-game-01",
      "attn": false,
      "task": "styled_tts",
      "lang": "en-GB",
      "style": "clipped military handler over comms, urgent but controlled",
      "title": "Mission briefing with item and danger callouts - Gaming",
      "script": "Raider, listen up. Extraction point is grid 7 4 2 9, north face of the Speranza Dam. You are carrying one Kestrel-pattern rebreather and three units of refined cobalt. Do not drop them. ARC patrols are heaviest between the silos, so move along the eastern wall instead. The storm front closes that corridor in nine minutes. If you miss the window, fall back to Cache Delta and hold for the next rotation. Good luck out there.",
      "target_rms_dbfs": -18.73,
      "pair": [
        {
          "clip": "c_ec5664960039",
          "gain": 0.8521
        },
        {
          "clip": "c_fb39296741c1",
          "gain": 1.0
        }
      ]
    },
    {
      "id": "vr-game-02",
      "attn": false,
      "task": "styled_tts",
      "lang": "en-US",
      "style": "esports commentator, escalating from level call to climax",
      "title": "Announcer escalation across five energy beats - Gaming",
      "script": "We're level at 14 to 14, ninety seconds on the clock. Vasquez has the cash box and she's moving. Kowalski is cutting the angle, he's going to catch her at the bridge. Oh, she jukes! She's through! Vasquez is through and the platform is lighting up! That is the steal of the tournament, and Ironhaus take it, 18 to 14!",
      "target_rms_dbfs": -18.93,
      "pair": [
        {
          "clip": "c_7d3d6033d3d3",
          "gain": 1.0
        },
        {
          "clip": "c_efc225a9d112",
          "gain": 0.5728
        }
      ]
    },
    {
      "id": "vr-game-03",
      "attn": false,
      "task": "styled_tts",
      "lang": "en-GB",
      "style": "in-world NPC, urgent, spoken mid-action",
      "title": "Real-time NPC response, time to first audio - Gaming",
      "script": "You should not have come this far alone, Raider. Turn back to the ridge and I will cover you.",
      "target_rms_dbfs": -18.25,
      "pair": [
        {
          "clip": "c_2a2ab6bdfc0c",
          "gain": 1.0
        },
        {
          "clip": "c_42f110f010c7",
          "gain": 0.9583
        }
      ]
    },
    {
      "id": "vr-game-04#engineer",
      "attn": false,
      "task": "styled_tts",
      "lang": null,
      "style": "station engineer, dry and matter of fact",
      "title": "Six distinct NPC voices - Gaming",
      "script": "The coupling is fine. The problem is whoever wired the relay backwards, and it was not me.",
      "target_rms_dbfs": -19.56,
      "pair": [
        {
          "clip": "c_bb9e3beffd6c",
          "gain": 0.9616
        },
        {
          "clip": "c_c32052ef2790",
          "gain": 1.0
        }
      ]
    },
    {
      "id": "vr-game-04#handler",
      "attn": false,
      "task": "styled_tts",
      "lang": null,
      "style": "mission handler over comms, firm and unhurried",
      "title": "Six distinct NPC voices - Gaming",
      "script": "Hold your position, Raider. Extraction is nine minutes out and the corridor is not clear.",
      "target_rms_dbfs": -16.68,
      "pair": [
        {
          "clip": "c_9b72a6d5c869",
          "gain": 1.0
        },
        {
          "clip": "c_b87a66c7e45e",
          "gain": 0.8091
        }
      ]
    },
    {
      "id": "vr-game-04#medic",
      "attn": false,
      "task": "styled_tts",
      "lang": null,
      "style": "field medic, warm and steady under pressure",
      "title": "Six distinct NPC voices - Gaming",
      "script": "Sit down and let me look at it. You are not walking anywhere on that leg, so stop arguing.",
      "target_rms_dbfs": -25.16,
      "pair": [
        {
          "clip": "c_25c1b72904b6",
          "gain": 1.0
        },
        {
          "clip": "c_540a9ec2f004",
          "gain": 0.2535
        }
      ]
    },
    {
      "id": "vr-game-04#quartermaster",
      "attn": false,
      "task": "styled_tts",
      "lang": null,
      "style": "weary quartermaster, past caring about rank",
      "title": "Six distinct NPC voices - Gaming",
      "script": "Supplies are short and the gate closes at dusk. Take what you need and be quick about it.",
      "target_rms_dbfs": -21.59,
      "pair": [
        {
          "clip": "c_24844549ecdb",
          "gain": 1.0
        },
        {
          "clip": "c_c7d7bf2ed0b4",
          "gain": 0.6509
        }
      ]
    },
    {
      "id": "vr-game-04#scout",
      "attn": false,
      "task": "styled_tts",
      "lang": null,
      "style": "young scout, clipped and alert",
      "title": "Six distinct NPC voices - Gaming",
      "script": "Movement on the ridge. Two of them, maybe three. I am not waiting to find out which.",
      "target_rms_dbfs": -19.23,
      "pair": [
        {
          "clip": "c_18f472da63e3",
          "gain": 0.5916
        },
        {
          "clip": "c_51c56ec4b99b",
          "gain": 1.0
        }
      ]
    },
    {
      "id": "vr-game-04#trader",
      "attn": false,
      "task": "styled_tts",
      "lang": null,
      "style": "market trader, bright and quick, always selling",
      "title": "Six distinct NPC voices - Gaming",
      "script": "Good salvage, that. I will give you four hundred for it, and we both know it is worth three.",
      "target_rms_dbfs": -20.21,
      "pair": [
        {
          "clip": "c_1879016a5387",
          "gain": 0.7023
        },
        {
          "clip": "c_2544e34a5aa8",
          "gain": 1.0
        }
      ]
    },
    {
      "id": "vr-game-07",
      "attn": false,
      "task": "text_to_speech",
      "lang": "en-GB",
      "style": null,
      "title": "Placeholder VO line, batch throughput - Gaming",
      "script": "Hold this position until the extraction window opens.",
      "target_rms_dbfs": -19.38,
      "pair": [
        {
          "clip": "c_0e478a308a9d",
          "gain": 0.7447
        },
        {
          "clip": "c_8373001a11fd",
          "gain": 1.0
        }
      ]
    },
    {
      "id": "attn-1",
      "attn": true,
      "task": "check",
      "lang": null,
      "style": null,
      "title": "Identical-pair check",
      "script": "Both clips below are the same recording. If they sound identical to you, choose “No preference”.",
      "target_rms_dbfs": null,
      "pair": [
        {
          "clip": "c_05eafabcdf8d",
          "gain": 1.0
        },
        {
          "clip": "c_05eafabcdf8d",
          "gain": 1.0
        }
      ]
    },
    {
      "id": "attn-2",
      "attn": true,
      "task": "check",
      "lang": null,
      "style": null,
      "title": "Identical-pair check",
      "script": "Both clips below are the same recording. If they sound identical to you, choose “No preference”.",
      "target_rms_dbfs": null,
      "pair": [
        {
          "clip": "c_e9e579b94010",
          "gain": 0.9215
        },
        {
          "clip": "c_e9e579b94010",
          "gain": 0.9215
        }
      ]
    }
  ]
};
